# Generated by Django 5.0.10 on 2025-02-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_photo_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Picture',
        ),
    ]
