# Generated by Django 5.0.10 on 2025-02-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_photo_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='gallery',
            new_name='album',
        ),
    ]
