# Generated by Django 5.0.10 on 2025-02-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_album_cover_alter_picture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_type',
            field=models.CharField(choices=[('default', '默认封面'), ('custom', '自定义封面')], default='default', max_length=10, verbose_name='封面类型'),
        ),
    ]
