# Generated by Django 5.0.10 on 2025-02-28 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_album_cover_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='main.album', verbose_name='相册'),
        ),
    ]
