# Generated by Django 5.0.10 on 2025-03-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_picture_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='picture_type',
            field=models.CharField(choices=[('user_upload', '用户上传'), ('default_cover', '默认相册封面')], default='user_upload', max_length=50),
        ),
    ]
