# Generated by Django 5.0.10 on 2025-03-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_label_picture_labels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Label',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='labels',
            new_name='tags',
        ),
    ]
