# Generated by Django 5.0.10 on 2025-03-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_label_tag_rename_labels_picture_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='tags',
            new_name='tag',
        ),
    ]
