# Generated by Django 5.0.10 on 2025-03-31 15:48

import django.utils.timezone
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='video',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='videos', to='main.tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='video',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='上传于'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=main.models.HashUploadTo(), verbose_name='视频'),
        ),
    ]
