# Generated by Django 5.0.10 on 2025-04-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_video_description_video_tag_video_upload_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '视频'},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='upload_at',
            new_name='uploaded_at',
        ),
    ]
